name: dbtsnow

profile: dbtsnow

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  dbtsnow:
    +schema: raw

models:
  dbtsnow:
    +static_analysis: strict
    # Materialize staging models as views, and marts as tables
    stg:
      +materialized: table
      +schema: stg
    mart:
      +materialized: table
      +schema: mart
